/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins.$pluginId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/$pluginId',
  path: '/$pluginId',
  getParentRoute: () => PluginsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/config': typeof ConfigRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/proxies': typeof ProxiesRoute
  '/signup': typeof SignupRoute
  '/terminal': typeof TerminalRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/plugins/': typeof PluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/config': typeof ConfigRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/preferences': typeof PreferencesRoute
  '/proxies': typeof ProxiesRoute
  '/signup': typeof SignupRoute
  '/terminal': typeof TerminalRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/plugins': typeof PluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/config': typeof ConfigRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/proxies': typeof ProxiesRoute
  '/signup': typeof SignupRoute
  '/terminal': typeof TerminalRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/plugins/': typeof PluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/config'
    | '/connect'
    | '/login'
    | '/playground'
    | '/plugins'
    | '/preferences'
    | '/proxies'
    | '/signup'
    | '/terminal'
    | '/plugins/$pluginId'
    | '/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/config'
    | '/connect'
    | '/login'
    | '/playground'
    | '/preferences'
    | '/proxies'
    | '/signup'
    | '/terminal'
    | '/plugins/$pluginId'
    | '/plugins'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/config'
    | '/connect'
    | '/login'
    | '/playground'
    | '/plugins'
    | '/preferences'
    | '/proxies'
    | '/signup'
    | '/terminal'
    | '/plugins/$pluginId'
    | '/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ConfigRoute: typeof ConfigRoute
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PluginsRoute: typeof PluginsRouteWithChildren
  PreferencesRoute: typeof PreferencesRoute
  ProxiesRoute: typeof ProxiesRoute
  SignupRoute: typeof SignupRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof PluginsRoute
    }
  }
}

interface PluginsRouteChildren {
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsPluginIdRoute: PluginsPluginIdRoute,
  PluginsIndexRoute: PluginsIndexRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ConfigRoute: ConfigRoute,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  PluginsRoute: PluginsRouteWithChildren,
  PreferencesRoute: PreferencesRoute,
  ProxiesRoute: ProxiesRoute,
  SignupRoute: SignupRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
